# GitHub Pages configuration for get.nimsforest.com
title: "NimsForest Package Manager"
description: "Bootstrap and manage organizational workspaces"

# Use minimal theme for clean URLs
theme: minima

# Custom domain
url: "https://get.nimsforest.com"

# Serve files without .html extension
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Custom MIME types for shell scripts
include:
  - install.sh
  - linux
  - macos  
  - windows

# Don't process these files through Jekyll
defaults:
  - scope:
      path: "linux"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "macos"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "windows"
    values:
      layout: null
      sitemap: false
  - scope:
      path: "install.sh"
    values:
      layout: null
      sitemap: false